### ISSUE TITLE
请问下有计划做系统托盘吗？

### ISSUE THREAD

**Issue by beyondkmp** [balthild/GTKlash#1]
现在已经非常好用了，要是有一个系统托盘就完美了！

**Comment by balthild** [comment]
`Gtk.StatusIcon` 在 GNOME 3.14 被 deprecated，在 3.26 彻底移除（成为 no-op）。

之后会考虑使用第三方实现如 `AppIndicator`。不过相关的几个 GNOME 插件暂不兼容 Wayland，无法调试。

Note: 
- https://github.com/phocean/TopIcons-plus
- https://github.com/ubuntu/gnome-shell-extension-appindicator

**Comment by balthild** [comment]
此外，直接关闭窗口时，程序是会在后台保持运行的。再次运行程序则会直接唤出窗口。

若要退出程序，需点击 Overview 界面的 Exit 按钮。

**Comment by beyondkmp** [comment]
了解了，多谢！！！

**Comment by balthild** [comment]
已添加托盘图标支持。GNOME 3.26+ 用户需安装这个扩展：[AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/)
